# Generated by Django 4.2.6 on 2023-11-08 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='coffee/media', verbose_name='Product Image (Width: 56 | Height: 84)')),
                ('normalprice', models.IntegerField(default=0, verbose_name='Normal Price')),
                ('smallprice', models.IntegerField(default=0, verbose_name='Small Price')),
                ('mediumprice', models.IntegerField(default=0, verbose_name='Medium Price')),
                ('largeprice', models.IntegerField(default=0, verbose_name='Large Price')),
                ('category', models.CharField(choices=[('COLD', 'COLD'), ('HOT', 'HOT')], default=False)),
                ('bestProduct', models.CharField(blank=True, choices=[('MUST TRY', 'MUST TRY'), ('BEST PRODUCT', 'BEST PRODUCT')], default='', verbose_name='Best Product or Must Try | Leave if None')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='OrdersInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffee/media')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='coffee.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='coffee/media')),
                ('normalprice', models.IntegerField(default=0)),
                ('smallprice', models.IntegerField(default=0)),
                ('mediumprice', models.IntegerField(default=0)),
                ('largeprice', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
