# Generated by Django 4.2.6 on 2023-11-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_remove_billingaddress_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='full_name',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
