# Generated by Django 4.2.6 on 2023-11-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_billingaddress_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('COLD', 'COLD'), ('HOT', 'HOT'), ('FOOD', 'FOOD')], default=False),
        ),
    ]
