# Generated by Django 4.2.6 on 2023-11-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='is_complete',
            field=models.CharField(choices=[('YES', 'YES')], default='', null=True),
        ),
    ]
