# Generated by Django 4.2.6 on 2023-11-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_userproductinadmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='full_name',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
