# Generated by Django 4.2.6 on 2023-11-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_completed_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
    ]
