# Generated by Django 4.2.6 on 2023-11-12 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_delete_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ordered', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
