# Generated by Django 4.2.6 on 2023-12-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0021_alter_billingaddress_is_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='is_what',
            field=models.CharField(choices=[('Order Received by Seller', 'Order Received by Seller'), ('Preparing', 'Preparing'), ('Out for delivery', 'Out for delivery')], default='ORDER RECEIVED BY SELLER', null=True),
        ),
    ]
